---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: test
  namespace: buildagent
spec:
  podIdentity:
    provider: azure-workload
---
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: test
  namespace: buildagent
spec:
  jobTargetRef:
    template:
      spec:
        initContainers:
        - name: get-token
          image: <image with az cli>
          imagePullPolicy: Always
          command: 
          - powershell
          - -Command
          - |
            az login `
              --service-principal `
              -u *** `
              --federated-token $(cat C:\k8s-token\token) `
              --tenant *** `
              --allow-no-subscriptions

            $azdo_token = az account get-access-token `
              --resource "https://management.core.windows.net/" `
              --query accessToken `
              --output tsv

            $azdo_token > /azdo-token/token
          volumeMounts:
          - name: azdo-token
            mountPath: /azdo-token
          - name: k8s-token
            mountPath: /k8s-token
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
        containers:
        - name: agent
          image: <buildagent image>
          imagePullPolicy: Always
          env:
          - name: AZP_URL
            value: https://dev.azure.com/<organization-name>/
          - name: AZP_POOL
            value: ***
          - name: AZP_TOKEN_FILE
            value: /azdo-token/token
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
          volumeMounts:
          - name: azdo-token
            mountPath: /azdo-token
        volumes:
        - name: azdo-token
          emptyDir: {}
        - name: k8s-token
          projected:
            sources:
            # service account with federated azure identity
            - serviceAccountToken:
                path: token
                expirationSeconds: 7200
                audience: api://AzureADTokenExchange
  minReplicaCount: 0
  maxReplicaCount: 5
  triggers:
  - type: azure-pipelines
    metadata:
      poolName: ***
      organizationURLFromEnv: AZP_URL
    authenticationRef:
      name: test